import { parseEther } from "viem";

export const SPEND_PERMISSION_REQUESTED_ALLOWANCE = 0.002;
export const SPEND_PERMISSION_REQUESTED_ALLOWANCE_WEI = parseEther(SPEND_PERMISSION_REQUESTED_ALLOWANCE.toString());